name: Get Azure AD Access Token

on:
  push:
    branches:
      - final # Modify to match your branch name

jobs:
  get-access-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install requests

    - name: Get Azure AD Access Token
      env:
        POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
        POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
        POWER_BI_TENANT_ID: ${{secrets.POWER_BI_TENANT_ID}}
        RESOURCE_URI: "https://analysis.windows.net/powerbi/api"
      run: |
        python - <<EOF
        import requests
        import os

        # Azure AD token endpoint
        token_url = f"https://login.microsoftonline.com/{os.environ['POWER_BI_TENANT_ID']}/oauth2/token"

        # Token request payload
        token_data = {
            "grant_type": "client_credentials",
            "client_id": os.environ['POWER_BI_CLIENT_ID'],
            "client_secret": os.environ['POWER_BI_CLIENT_SECRET'],
            "resource": os.environ['RESOURCE_URI']
        }

        # Request token
        response = requests.post(token_url, data=token_data)
        token = response.json().get('access_token', '')

        print(f"::set-output name=access_token::{token}")
  use-access-token:
    needs: get-access-token
    runs-on: ubuntu-latest
    steps:
      - name: Use Access Token
        env:
          ACCESS_TOKEN: ${{ steps.get-access-token.outputs.access_token }}
        run: |
          echo "Access Token: $ACCESS_TOKEN"

      - name: Update Power BI Dataset Parameters
        env:
          POWER_BI_API_URL: https://api.powerbi.com/v1.0/myorg/datasets/84a1fea6-a146-4316-8aa6-5ce61bee7e34/Default.UpdateParameters
          POWER_BI_ACCESS_TOKEN: $ACCESS_TOKEN
        run: |
          payload='{
            "updateDetails": [
              {
              "name": "DatabaseName",
              "newValue": "devidata"
              },
              {
              "name": "server",
              "newValue": "devidata.database.windows.net"
              }
            ]
          }'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $POWER_BI_API_TOKEN" -d "$payload" "$POWER_BI_API_URL"
  
  

    
  
