name: Power BI Deployment with Dataset Parameter Update

on:
  push:
    branches:
      - final

env:
  POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
  POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
  POWER_BI_TENANT_ID: ${{secrets.POWER_BI_TENANT_ID}}
  POWER_BI_WORKSPACE_ID: ${{secrets.POWER_BI_WORKSPACE_ID}}
  PBIX_FILE_PATH: ./finaldashboard.pbix
  DATASET_NAME: finaldashboard
  REPORT_NAME: finaldashboard.pbix
  DOTNET_INSTALL_DIR: "runner/dotnet"
  AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}

jobs:
  pbix_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Power BI CLI
        run: |
          npm i -g @powerbi-cli/powerbi-cli

      - name: Authenticate Power BI CLI azure
        run: |
          az login --service-principal -u ${{env.POWER_BI_CLIENT_ID}} -p ${{env.POWER_BI_CLIENT_SECRET}} --tenant ${{env.POWER_BI_TENANT_ID}} 
          export POWER_BI_ACCESS_TOKEN=$(az account get-access-token --resource https://analysis.windows.net/)
          echo "POWER_BI_ACCESS_TOKEN=$POWER_BI_ACCESS_TOKEN" >> $GITHUB_ENV
          pbicli login --interactive
         # pbicli login --service-principal -p ${{env.POWER_BI_CLIENT_ID}} -s ${{env.POWER_BI_CLIENT_SECRET}} -t ${{env.POWER_BI_TENANT_ID}}
          
      - name: Import PBIX File
        run: |
          pbicli import pbix --workspace ${{env.POWER_BI_WORKSPACE_ID}} --file ${{env.PBIX_FILE_PATH}} --name ${{env.DATASET_NAME}} --conflict CreateOrOverwrite

      - name: List Dataset Parameters
        run: |
          pbicli dataset parameter list --workspace ${{env.POWER_BI_WORKSPACE_ID}} --dataset ${{env.DATASET_NAME}}

  upadte_params:
    runs-on: ubuntu-latest
    needs: pbix_deploy

    steps:
      - name: Set up PowerShell
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
        env:
          PSGALLERYApiKey: ${{ secrets.PSGALLERY_API_KEY }}

      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ env.POWER_BI_CLIENT_ID }}", "clientSecret":"${{ env.POWER_BI_CLIENT_SECRET }}", "subscriptionId":"${{ env.AZURE_SUBSCRIPTION_ID }}", "tenantId":"${{ env.POWER_BI_TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Log in to Power BI
        run: |
          Connect-PowerBIServiceAccount -ServicePrincipal -ApplicationId 647b60eb-374e-4af1-b7c7-439ba4913814 -Tenant 0277ec7c-6485-4a45-9d8e-07a6941a7819



    
  
