name: Power BI Deployment with Dataset Parameter Update

on:
  push:
    branches:
      - test

env:
  POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
  POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
  POWER_BI_TENANT_ID: ${{secrets.POWER_BI_TENANT_ID}}
  POWER_BI_WORKSPACE_ID: ${{secrets.POWER_BI_WORKSPACE_ID}}
  PBIX_FILE_PATH: ./finaldashboard.pbix
  DATASET_NAME: finaldashboard
  REPORT_NAME: finaldashboard.pbix
  DOTNET_INSTALL_DIR: "runner/dotnet"
  POWER_BI_DATASET_ID: ${{secrets.POWER_BI_DATASET_ID}}

jobs:
  pbix_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Power BI CLI
        run: |
          npm i -g @powerbi-cli/powerbi-cli

      - name: Authenticate Power BI CLI
        run: |
          pbicli login --service-principal -p ${{env.POWER_BI_CLIENT_ID}} -s ${{env.POWER_BI_CLIENT_SECRET}} -t ${{env.POWER_BI_TENANT_ID}}
          
      - name: Import PBIX File
        run: |
          pbicli import pbix --workspace ${{env.POWER_BI_WORKSPACE_ID}} --file ${{env.PBIX_FILE_PATH}} --name ${{env.DATASET_NAME}} --conflict CreateOrOverwrite

      - name: List Dataset Parameters
        run: |
          pbicli dataset parameter list --workspace ${{env.POWER_BI_WORKSPACE_ID}} --dataset ${{env.DATASET_NAME}}

      
      - name: Obtain Power BI API Token 
        id: get-token
        run: |
          response=$(curl -X POST -d "grant_type=client_credentials" \
            -d "client_id=$POWER_BI_CLIENT_ID" \
            -d "client_secret=$POWER_BI_CLIENT_SECRET" \
            -d "scope=https://analysis.windows.net/powerbi/api/.default" \
            "https://login.microsoftonline.com/$POWER_BI_TENANT_ID/oauth2/token")
          access_token=$(echo "$response" | jq -r '.access_token'
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Make POST request to update dataset parameters
        run: |
          DATASET_ID=$POWER_BI_DATASET_ID
          ACCESS_TOKEN=$INPUT_ACCESS_TOKEN
          JSON_PAYLOAD='{
            "updateDetails": [
              {
                "name": "DatabaseName",
                "newValue": "NewDB"
              },
              {
                "name": "MaxId",
                "newValue": "5678"
              }
            ]
          }'
          curl -X POST \
            "https://api.powerbi.com/v1.0/myorg/datasets/${DATASET_ID}/Default.UpdateParameters" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
        env:
          INPUT_ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
          DATASET_ID: ${{env.POWER_BI_DATASET_ID}}
          
          

      - name: Update Dataset Parameters
        run: |
          # Here, update dataset parameters using the contents of your parameter file
          curl -X POST \
            https://api.powerbi.com/v1.0/myorg/datasets/{datasetId}/Default.UpdateParameters
      - name: Datasource update
        run: |
          pbicli dataset datasource list --workspace ${{env.POWER_BI_WORKSPACE_ID}} --dataset ${{env.DATASET_NAME}}
          #pbicli dataset datasource update --workspace ${{env.POWER_BI_WORKSPACE_ID}} --dataset ${{env.DATASET_NAME}}  --update-details @{./datasource.json}
