name: Power BI Deployment with Dataset Parameter Update

on:
  push:
    branches:
      - main

env:
  POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
  POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
  POWER_BI_TENANT_ID: ${{secrets.POWER_BI_TENANT_ID}}
  POWER_BI_WORKSPACE_ID: ${{secrets.POWER_BI_WORKSPACE_ID}}
  PBIX_FILE_PATH: ./devreport0001.pbix
  DATASET_NAME: devreport0001
  REPORT_NAME: devreport0001.pbix
  DOTNET_INSTALL_DIR: "runner/dotnet"

jobs:
  pbix_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Power BI CLI
        run: |
          npm i -g @powerbi-cli/powerbi-cli

      - name: Authenticate Power BI CLI
        run: |
          pbicli login --service-principal -p ${{env.POWER_BI_CLIENT_ID}} -s ${{env.POWER_BI_CLIENT_SECRET}} -t ${{env.POWER_BI_TENANT_ID}}
          
      - name: Import PBIX File
        run: |
          pbicli import pbix --workspace ${{env.POWER_BI_WORKSPACE_ID}} --file ${{env.PBIX_FILE_PATH}} --name ${{env.DATASET_NAME}} --conflict CreateOrOverwrite

      - name: List Dataset Parameters
        run: |
          pbicli dataset parameter list --workspace ${{env.POWER_BI_WORKSPACE_ID}} --dataset ${{env.DATASET_NAME}}

      - name: Update Dataset Parameters
        run: |
          # Here, update dataset parameters using the contents of your parameter file
          pbicli dataset parameter update --workspace ${{env.POWER_BI_WORKSPACE_ID}} --dataset ${{env.DATASET_NAME}} --parameter "{\"updateDetails\":[{\"name\":\"Server\",\"newValue\":\"dev0001.database.windows.net\"},{\"name\":\"Database\",\"newValue\":\"dev\"},{\"name\":\"BatchNumber\",\"newValue\":\"100\"}]}" --verbose --verbose
