name: Deploy Power BI Dataset

on:
  push:
    branches:
      - rrr

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AZ PowerShell set-up
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az

      - name: Install Power BI PowerShell module
        shell: pwsh
        run: Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser

      - name: Import Power BI module
        shell: pwsh
        run: Import-Module MicrosoftPowerBIMgmt

      - name: Publish PBIX to Power BI Workspace
        env:
          POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
          POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
          POWER_BI_WORKSPACE_ID: ${{secrets.POWER_BI_WORKSPACE_ID}}
        run: |
          $PowerBISession = New-PowerBISession -ClientId $env:POWER_BI_CLIENT_ID -ClientSecret $env:POWER_BI_CLIENT_SECRET -ErrorAction Stop
          Set-PowerBISession -PowerBISession $PowerBISession -ErrorAction Stop
          
          $PBIXFilePath = "./devreport0001.pbix"  # Update with your .pbix file path
          $DatasetName = "devreport0001"      # Update with your dataset name
          $TargetWorkspaceId = $env:POWER_BI_WORKSPACE_ID

          Publish-PowerBIFile -Path $PBIXFilePath -Name $DatasetName -WorkspaceId $TargetWorkspaceId -ErrorAction Stop

      - name: Update Dataset Parameters
        env:
          POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
          POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
          POWER_BI_WORKSPACE_ID: ${{ secrets.POWER_BI_WORKSPACE_ID }}
        run: |
          $PowerBISession = New-PowerBISession -ClientId $env:POWER_BI_CLIENT_ID -ClientSecret $env:POWER_BI_CLIENT_SECRET -ErrorAction Stop
          Set-PowerBISession -PowerBISession $PowerBISession -ErrorAction Stop
          
          $DatasetId = Get-PowerBIDataset -Name $DatasetName -WorkspaceId $env:POWER_BI_WORKSPACE_ID | Select-Object -ExpandProperty Id
          $Parameters = @(
            @{
              Name = "Server"
              Type = "Text"
              Values = "Sit"
            },
            @{
              Name = "Database"
              Type = "Text"
              Values = "SQLDB"
            }
          )  # Define your parameter updates here

          Set-PowerBIDatasetParameter -DatasetId $DatasetId -Parameters $Parameters -ErrorAction Stop
