name: Deploy Power BI Dataset

on:
  push:
    branches:
      - rrr

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: AZ PowerShell set-up
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az

      - name: Install Power BI PowerShell module
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt
          Install-Module -Name MicrosoftPowerBIMgmt.Workspaces
          Update-Module -Name MicrosoftPowerBIMgmt

      - name: Import Power BI module
        shell: pwsh
        run: Import-Module MicrosoftPowerBIMgmt

      - name: Authenticate with Power BI
        shell: pwsh
        env:
          POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
          POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
          POWER_BI_WORKSPACE_ID: ${{secrets.POWER_BI_WORKSPACE_ID}}
          POWER_BI_TENANT_ID: ${{secrets.POWER_BI_TENANT_ID}}
        run: |
          $PbiServiceAccount = Connect-PowerBIServiceAccount -ServicePrincipal -ClientId $env:POWER_BI_CLIENT_ID -ClientSecret $env:POWER_BI_CLIENT_SECRET -TenantId $env:POWER_BI_TENANT_ID -ErrorAction Stop
      - name: Publish PBIX to Power BI Workspace 
        env:
          POWER_BI_WORKSPACE_ID: ${{secrets.POWER_BI_WORKSPACE_ID}}
        run: |
          $PBIXFilePath = "./devreport0001.pbix"  # Update with your .pbix file path
          $DatasetName = "devreport0001"      # Update with your dataset name
          $TargetWorkspaceId = $env:POWER_BI_WORKSPACE_ID
          Publish-PowerBIFile -Path $PBIXFilePath -Name $DatasetName -WorkspaceId $TargetWorkspaceId -ErrorAction Stop

      - name: Update Dataset Parameters
        env:
          POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
          POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
          POWER_BI_WORKSPACE_ID: ${{ secrets.POWER_BI_WORKSPACE_ID }}
        run: |
          $DatasetName = "devreport0001"
          $Parameters = @(
            @{
              Name = "Server"
              Type = "Text"
              Values = "Sit"
            },
            @{
              Name = "Database"
              Type = "Text"
              Values = "SQLDB"
            }
          )  # Define your parameter updates here

          $ApiUrl = "https://api.powerbi.com/v1.0/myorg/groups/$($env:POWER_BI_WORKSPACE_ID)/datasets/$($DatasetName)/Default.UpdateParameters"
          $ApiRequestBody = @{
            updateDetails = $Parameters
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $ApiUrl -Method Post -Headers @{Authorization = "Bearer $($PbiServiceAccount.AccessToken)"} -Body $ApiRequestBody -ContentType "application/json"

          Set-PowerBIDatasetParameter -DatasetId $DatasetId -Parameters $Parameters -ErrorAction Stop
