name: Dataset Parameters

on:
  push:
    branches:
      - update-0001

jobs:
  update-dataset-parameters:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Run PowerShell script
        shell: pwsh
        run: |
          # Run the PowerShell script
          ./update_dataset_parameters.ps1
        env:
          POWER_BI_CLIENT_ID: ${{ secrets.POWER_BI_CLIENT_ID }}
          POWER_BI_CLIENT_SECRET: ${{ secrets.POWER_BI_CLIENT_SECRET }}
          POWER_BI_TENANT_ID: ${{ secrets.POWER_BI_TENANT_ID }}
          POWER_BI_WORKSPACE_NAME: ${{ secrets.POWER_BI_WORKSPACE_NAME }}
          POWER_BI_DATASET_NAME: ${{ secrets.POWER_BI_DATASET_NAME }}
