name: Update Power BI Parameters

on:
  push:
    paths:
      - '**/*.pbix'

jobs:
  update_parameters:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run shell script
        uses: PowerShell/action@v1
        with:
          script: ./update_dataset_parameters.ps1 # Change this to the path of your shell script
