name: Update Power BI Parameters

on:
  push:
    branches:
      - update-003

jobs:
  update_parameters:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Power BI PowerShell Module
        run: Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser

      - name: Run shell script
        shell: pwsh
        run: |
          ./update_dataset_parameters.ps1 # Change this to the path of your shell script
