name: Power BI Deployment

on:
  push:
    branches:
      - powershell
env:
  POWER_BI_CLIENT_ID: ${{secrets.POWER_BI_CLIENT_ID}}
  POWER_BI_CLIENT_SECRET: ${{secrets.POWER_BI_CLIENT_SECRET}}
  POWER_BI_TENANT_ID: ${{secrets.POWER_BI_TENANT_ID}}
  POWER_BI_WORKSPACE_ID: ${{secrets.POWER_BI_WORKSPACE_ID}}
  PBIX_FILE_PATH: ./finaldashboard.pbix
  DATASET_NAME: finaldashboard
  REPORT_NAME: finaldashboard.pbix
  DOTNET_INSTALL_DIR: "runner/dotnet"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Power BI CLI
        run: |
          npm i -g @powerbi-cli/powerbi-cli

      - name: Authenticate Power BI CLI
        run: |
          pbicli login --service-principal -p ${{env.POWER_BI_CLIENT_ID}} -s ${{env.POWER_BI_CLIENT_SECRET}} -t ${{env.POWER_BI_TENANT_ID}}
          
      - name: Import PBIX File
        run: |
          pbicli import pbix --workspace ${{env.POWER_BI_WORKSPACE_ID}} --file ${{env.PBIX_FILE_PATH}} --name ${{env.DATASET_NAME}} --conflict CreateOrOverwrite

      - name: Set up PowerShell
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser
        env:
          PSGALLERYApiKey: ${{ secrets.PSGALLERY_API_KEY }}

      - name: Set up environment
        run: |
          $ParamDbName: "database" # Replace with the name of the parameter to update
          $DbName: "devidata"  # Replace with the new value for the parameter
          $ParamDbServerName: "Server" # Replace with the name of the server name parameter
          $DbServer: "devidata.database.windows.net" # Replace with the new server name value
          $WorkspaceId: "96b1ab18-cd5e-4e01-8ffd-8bf59651f1bf" # Replace with your Power BI workspace ID
          $DatasetId: "6bd5bd3b-4af9-4e6c-9151-4cca6cbb6ed5" # Replace with your dataset ID
        env:
          PARAM_DB_NAME: $ParamDbName
          DB_NAME: $DbName
          PARAM_DB_SERVER_NAME: $ParamDbServerName
          DB_SERVER: $DbServer
          WORKSPACE_ID: $WorkspaceId
          DATASET_ID: $DatasetId

      - name: Update Dataset Parameters
        run: |
          $Parameters: @{
            "updateDetails": @(
                @{
                    "name"="$env:PARAM_DB_NAME";
                    "newValue"="$env:DB_NAME";
                },
                @{
                    "name"="$env:PARAM_DB_SERVER_NAME";
                    "newValue"="$env:DB_SERVER";
                }            
            )
          }
          $ParametersJson = $Parameters | ConvertTo-Json -Compress
          $AccessToken = $(az account get-access-token --query accessToken -o tsv)
          $Headers = @{
            'Authorization' = "Bearer $AccessToken"
            'Content-Type' = 'application/json'
          }
          $Url = "https://api.powerbi.com/v1.0/myorg/groups/$($env:WORKSPACE_ID)/datasets/$($env:DATASET_ID)/Default.UpdateParameters"
          Invoke-RestMethod -Method Post -Uri $Url -Headers $Headers -Body $ParametersJson
